[project]
name = "backend-skeleton"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic>=2.7",
    "pydantic-settings>=2.3",
    "python-multipart",
]

[tool.ruff]
line-length = 100