"""
Template schema contract — Pydantic models.

This is the single source of truth for template field definitions.
Everything else (fill engine, validation, LLM prompts, derived JSON-schemas)
operates against this model, never against raw ``template_schema`` JSONB blobs.

Key concepts
------------
- *Scalar* field  — one value substituted via ``{{key}}`` token anywhere in the file.
- *Table* field   — repeating region (rows or columns) located via a *marker-loop*
  (explicit ``{{table.col}}`` tokens) or a *structural* anchor (header text matching).
- *Provenance*    — ``source`` records whether a field was generated by LLM or set by
  an admin; ``locked`` prevents re-analysis from overwriting admin edits.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, field_validator, model_validator

CONTRACT_VERSION = "1.0"

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class FieldKind(str, Enum):
    SCALAR = "scalar"
    TABLE = "table"


class FieldType(str, Enum):
    STRING = "string"
    NUMBER = "number"
    DATE = "date"
    BOOL = "bool"
    ENUM = "enum"


class Orientation(str, Enum):
    VERTICAL = "vertical"    # table grows downward (clone rows)
    HORIZONTAL = "horizontal"  # table grows rightward (clone columns)


class FieldSource(str, Enum):
    LLM = "llm"
    ADMIN = "admin"
    PARSER = "parser"  # deterministic parser, no LLM


class AnchorStrategy(str, Enum):
    AUTO = "auto"        # marker if present, structural fallback
    MARKER = "marker"    # marker-loop only
    STRUCTURAL = "structural"  # header-based only


class DocumentFormat(str, Enum):
    EXCEL = "excel"
    DOCX = "docx"
    TEXT = "text"


# ---------------------------------------------------------------------------
# Locators
# ---------------------------------------------------------------------------


class TokenLocator(BaseModel):
    """Token-based locator for scalar fields or table columns."""
    token: str = Field(..., description="Full placeholder token, e.g. '{{applicant_name}}'")

    @field_validator("token")
    @classmethod
    def _strip(cls, v: str) -> str:
        return v.strip()


# ---------------------------------------------------------------------------
# Anchor definitions for table fields
# ---------------------------------------------------------------------------


class MarkerAnchor(BaseModel):
    """Marker-loop anchor: the template row contains explicit column tokens."""
    loop_tokens: List[str] = Field(
        ...,
        description="List of column tokens present in the marker row, e.g. ['{{items.name}}', '{{items.qty}}']",
        min_length=1,
    )


class StructuralAnchor(BaseModel):
    """Structural anchor: table is located by its header text."""
    header_signature: List[str] = Field(
        ...,
        description="Ordered list of header cell texts to match (fuzzy).",
        min_length=1,
    )
    match: str = Field("fuzzy", description="'exact' or 'fuzzy'")
    template_row: str = Field(
        "first_after_header",
        description="Which row to use as the clone template: 'first_after_header'.",
    )


class TableAnchor(BaseModel):
    """Combined anchor — supports marker-loop and/or structural strategy."""
    sheet: Optional[str] = Field(None, description="Sheet name (Excel only).")
    strategy: AnchorStrategy = AnchorStrategy.AUTO
    marker: Optional[MarkerAnchor] = None
    structural: Optional[StructuralAnchor] = None

    @model_validator(mode="after")
    def _check_strategy_data(self) -> "TableAnchor":
        if self.strategy == AnchorStrategy.MARKER and not self.marker:
            raise ValueError("strategy='marker' requires marker to be set")
        if self.strategy == AnchorStrategy.STRUCTURAL and not self.structural:
            raise ValueError("strategy='structural' requires structural to be set")
        return self


# ---------------------------------------------------------------------------
# Column definition (used inside TableField)
# ---------------------------------------------------------------------------


class TableColumn(BaseModel):
    key: str = Field(..., min_length=1)
    label: str = Field(..., min_length=1)
    description: Optional[str] = None
    type: FieldType = FieldType.STRING
    required: bool = True
    example: Optional[str] = None
    locator: Optional[TokenLocator] = None
    source: FieldSource = FieldSource.LLM
    locked: bool = False


# ---------------------------------------------------------------------------
# Field types
# ---------------------------------------------------------------------------


class ScalarField(BaseModel):
    key: str = Field(..., min_length=1)
    kind: FieldKind = FieldKind.SCALAR
    label: str = Field(..., min_length=1)
    description: Optional[str] = None
    type: FieldType = FieldType.STRING
    required: bool = True
    example: Optional[str] = None
    enum: Optional[List[str]] = None
    format: Optional[str] = Field(None, description="Format hint, e.g. 'DD.MM.YYYY' for dates.")
    locator: Optional[TokenLocator] = None
    source: FieldSource = FieldSource.LLM
    locked: bool = False

    @model_validator(mode="after")
    def _enum_requires_type(self) -> "ScalarField":
        if self.enum and self.type != FieldType.ENUM:
            raise ValueError("'enum' list provided but type is not 'enum'")
        return self


class TableField(BaseModel):
    key: str = Field(..., min_length=1)
    kind: FieldKind = FieldKind.TABLE
    label: str = Field(..., min_length=1)
    description: Optional[str] = None
    orientation: Orientation = Orientation.VERTICAL
    required: bool = True
    min_rows: int = Field(1, ge=0)
    max_rows: Optional[int] = Field(None, ge=1)
    anchor: Optional[TableAnchor] = None
    columns: List[TableColumn] = Field(default_factory=list, min_length=1)
    source: FieldSource = FieldSource.LLM
    locked: bool = False

    @model_validator(mode="after")
    def _max_gte_min(self) -> "TableField":
        if self.max_rows is not None and self.max_rows < self.min_rows:
            raise ValueError("max_rows must be >= min_rows")
        return self


AnyField = Union[ScalarField, TableField]


# ---------------------------------------------------------------------------
# Top-level contract
# ---------------------------------------------------------------------------


class TemplateContract(BaseModel):
    contract_version: str = Field(CONTRACT_VERSION)
    format: Optional[DocumentFormat] = None
    fields: List[AnyField] = Field(default_factory=list)

    # ------------------------------------------------------------------
    # Derived: fill_input_schema
    # ------------------------------------------------------------------

    def to_fill_input_schema(self) -> Dict[str, Any]:
        """Return a JSON-Schema-like dict describing the ``values`` payload for fill.

        Scalars  → flat typed key
        Tables   → array of objects built from column definitions
        """
        properties: Dict[str, Any] = {}
        required: List[str] = []

        for field in self.fields:
            if isinstance(field, ScalarField):
                prop: Dict[str, Any] = {"type": field.type.value}
                if field.description:
                    prop["description"] = field.description
                if field.example is not None:
                    prop["example"] = field.example
                if field.enum:
                    prop["enum"] = field.enum
                if field.format:
                    prop["format"] = field.format
                properties[field.key] = prop
                if field.required:
                    required.append(field.key)

            elif isinstance(field, TableField):
                col_props: Dict[str, Any] = {}
                col_required: List[str] = []
                for col in field.columns:
                    cp: Dict[str, Any] = {"type": col.type.value}
                    if col.description:
                        cp["description"] = col.description
                    if col.example is not None:
                        cp["example"] = col.example
                    col_props[col.key] = cp
                    if col.required:
                        col_required.append(col.key)

                item_schema: Dict[str, Any] = {
                    "type": "object",
                    "properties": col_props,
                }
                if col_required:
                    item_schema["required"] = col_required

                table_prop: Dict[str, Any] = {
                    "type": "array",
                    "items": item_schema,
                }
                if field.description:
                    table_prop["description"] = field.description
                if field.min_rows:
                    table_prop["minItems"] = field.min_rows
                if field.max_rows is not None:
                    table_prop["maxItems"] = field.max_rows
                properties[field.key] = table_prop
                if field.required:
                    required.append(field.key)

        schema: Dict[str, Any] = {"type": "object", "properties": properties}
        if required:
            schema["required"] = required
        return schema

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def validate_values(self, values: Dict[str, Any]) -> "ValidationReport":
        """Validate ``values`` against this contract.

        Checks:
        - required scalars present and non-empty
        - required tables present, non-empty, and satisfying min/max_rows
        - type coercion sanity for known primitive types
        - unknown top-level keys (warning, not error)
        """
        errors: List[str] = []
        warnings: List[str] = []

        contract_keys = {f.key for f in self.fields}
        for k in values:
            if k not in contract_keys:
                warnings.append(f"Unknown key '{k}' — not in contract")

        for field in self.fields:
            val = values.get(field.key)

            if isinstance(field, ScalarField):
                if field.required and (val is None or (isinstance(val, str) and not val.strip())):
                    errors.append(f"Required scalar '{field.key}' is missing or empty")
                    continue
                if val is not None:
                    type_err = _check_scalar_type(field.key, val, field.type)
                    if type_err:
                        errors.append(type_err)

            elif isinstance(field, TableField):
                if field.required and (val is None or val == []):
                    errors.append(f"Required table '{field.key}' is missing or empty")
                    continue
                if val is not None:
                    if not isinstance(val, list):
                        errors.append(f"Table '{field.key}' must be an array, got {type(val).__name__}")
                        continue
                    n = len(val)
                    if n < field.min_rows:
                        errors.append(
                            f"Table '{field.key}' has {n} row(s), but min_rows={field.min_rows}"
                        )
                    if field.max_rows is not None and n > field.max_rows:
                        errors.append(
                            f"Table '{field.key}' has {n} row(s), but max_rows={field.max_rows}"
                        )
                    col_keys = {c.key for c in field.columns}
                    req_cols = {c.key for c in field.columns if c.required}
                    for i, row in enumerate(val):
                        if not isinstance(row, dict):
                            errors.append(f"Table '{field.key}' row[{i}] must be an object")
                            continue
                        for ck in row:
                            if ck not in col_keys:
                                warnings.append(
                                    f"Table '{field.key}' row[{i}] has unknown column '{ck}'"
                                )
                        for ck in req_cols:
                            rv = row.get(ck)
                            if rv is None or (isinstance(rv, str) and not rv.strip()):
                                errors.append(
                                    f"Table '{field.key}' row[{i}] missing required column '{ck}'"
                                )

        return ValidationReport(errors=errors, warnings=warnings)

    # ------------------------------------------------------------------
    # Field lookup helpers
    # ------------------------------------------------------------------

    def get_field(self, key: str) -> Optional[AnyField]:
        for f in self.fields:
            if f.key == key:
                return f
        return None

    def scalar_fields(self) -> List[ScalarField]:
        return [f for f in self.fields if isinstance(f, ScalarField)]

    def table_fields(self) -> List[TableField]:
        return [f for f in self.fields if isinstance(f, TableField)]

    # ------------------------------------------------------------------
    # Serialization helpers
    # ------------------------------------------------------------------

    def to_jsonb(self) -> Dict[str, Any]:
        """Serialize to dict suitable for storing in JSONB column."""
        return self.model_dump(mode="json", exclude_none=False)

    @classmethod
    def from_jsonb(cls, data: Optional[Dict[str, Any]]) -> "TemplateContract":
        """Deserialize from JSONB dict, with back-compat for old format.

        Old format: ``{format, sheets, placeholders}`` or ``{format, draft_schema}``
        → returns empty contract without raising.
        """
        if not data:
            return cls()
        if "contract_version" not in data:
            return cls()
        try:
            return cls.model_validate(data)
        except Exception:
            return cls()


# ---------------------------------------------------------------------------
# ValidationReport
# ---------------------------------------------------------------------------


class ValidationReport(BaseModel):
    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)

    @property
    def ok(self) -> bool:
        return len(self.errors) == 0

    def raise_if_invalid(self) -> None:
        if not self.ok:
            raise ValueError(f"Contract validation failed: {'; '.join(self.errors)}")


# ---------------------------------------------------------------------------
# merge_contract
# ---------------------------------------------------------------------------


def merge_contract(
    existing: TemplateContract,
    proposed: TemplateContract,
) -> TemplateContract:
    """Merge *proposed* (from LLM/parser re-analysis) into *existing* contract.

    Rules
    -----
    - Fields in *existing* with ``locked=True`` or ``source=FieldSource.ADMIN``
      are **never** modified or removed.
    - Unlocked ``source=llm`` fields in *existing* are replaced by the corresponding
      proposed field (matched by ``key``).
    - New keys in *proposed* that are absent from *existing* are appended.
    - Keys present in *existing* with source=llm but absent from *proposed* are removed
      (they no longer appear in the template).
    - The top-level ``format`` is updated from *proposed* unless *existing* format
      was set by an admin (currently: always update format from proposed).
    """
    protected: Dict[str, AnyField] = {}
    llm_existing: Dict[str, AnyField] = {}

    for f in existing.fields:
        if f.locked or f.source == FieldSource.ADMIN:
            protected[f.key] = f
        else:
            llm_existing[f.key] = f

    merged_fields: List[AnyField] = []

    # Keep protected fields in their original order
    for key, pf in protected.items():
        merged_fields.append(pf)

    # Add/update from proposed (skipping protected keys)
    for pf in proposed.fields:
        if pf.key in protected:
            continue  # protected — not touched
        merged_fields.append(pf)

    # Preserve format from proposed if available
    new_format = proposed.format or existing.format

    return TemplateContract(
        contract_version=CONTRACT_VERSION,
        format=new_format,
        fields=merged_fields,
    )


# ---------------------------------------------------------------------------
# Type checking helper
# ---------------------------------------------------------------------------


def _check_scalar_type(key: str, value: Any, expected: FieldType) -> Optional[str]:
    if expected == FieldType.NUMBER:
        if not isinstance(value, (int, float)):
            try:
                float(str(value))
            except (ValueError, TypeError):
                return f"Scalar '{key}' expected number, got '{value}'"
    elif expected == FieldType.BOOL:
        if not isinstance(value, bool) and str(value).lower() not in ("true", "false", "1", "0"):
            return f"Scalar '{key}' expected bool, got '{value}'"
    # string, date, enum — accept anything; enum value checking left to callers
    return None
