#!/usr/bin/env bash

set -euo pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${script_dir}/common.sh"

release_phase_start "preflight release checks"
bash "${script_dir}/release-check.sh"
release_phase_end

release_phase_start "load release metadata"
load_release_file

origin_release_sha="$(git -C "$REPO_ROOT" rev-parse origin/main)"
next_app_tag="$(bump_app_patch "$APP_IMAGE_TAG")"
next_base_tag="$BASE_IMAGE_TAG"
next_base_sha="$(base_input_sha)"
base_ref="${IMAGE_REPOSITORY}/base-ml:${BASE_IMAGE_TAG}"
api_image="${IMAGE_REPOSITORY}/api:${next_app_tag}"
release_log "Current app=${APP_IMAGE_TAG}, next app=${next_app_tag}, base=${BASE_IMAGE_TAG}"
release_log "Calculated base input SHA=${next_base_sha}"
release_phase_end

ensure_base_available() {
  local local_base="ml-portal-base-ml:${BASE_IMAGE_TAG}"
  if docker image inspect "$base_ref" >/dev/null 2>&1; then
    release_log "Base image already exists locally: ${base_ref}"
    return
  fi
  if docker image inspect "$local_base" >/dev/null 2>&1; then
    release_log "Using local base ${local_base}; tagging it as ${base_ref}"
    docker tag "$local_base" "$base_ref"
    return
  fi
  release_log "Base image is not local; pulling ${base_ref}"
  docker pull "$base_ref"
}

release_phase_start "check immutable app image"
if docker manifest inspect "$api_image" >/dev/null 2>&1; then
  fail "Refusing to overwrite immutable release image already present in registry: ${api_image}"
fi
release_phase_end

release_phase_start "prepare base image"
if test "$next_base_sha" != "$BASE_INPUT_SHA"; then
  next_base_tag="$(bump_base_minor "$BASE_IMAGE_TAG")"
  next_base_ref="${IMAGE_REPOSITORY}/base-ml:${next_base_tag}"
  if docker manifest inspect "$next_base_ref" >/dev/null 2>&1; then
    fail "Refusing to overwrite immutable base image already present in registry: ${next_base_ref}"
  fi
  echo "Base inputs changed; publishing ${next_base_ref}"
  if ! docker pull "$base_ref"; then
    release_log "WARN: previous base image ${base_ref} is unavailable; continuing without cache"
  fi
  docker build --cache-from "$base_ref" -t "$next_base_ref" -f "$BASE_DOCKERFILE" "$REPO_ROOT"
  docker push "$next_base_ref"
  base_ref="$next_base_ref"
else
  echo "Base inputs unchanged; ensuring ${base_ref} is available"
  ensure_base_available
fi
release_log "Using base image ${base_ref}"
release_phase_end

release_phase_start "build service images"
echo "Building service images with ${base_ref} and tag ${next_app_tag}"
BUILDKIT_PROGRESS=plain BASE_IMAGE="$base_ref" IMAGE_REPOSITORY="$IMAGE_REPOSITORY" APP_IMAGE_TAG="$next_app_tag" \
  docker compose -f "${REPO_ROOT}/docker-compose.build.yml" build
release_phase_end

release_phase_start "push service images"
BASE_IMAGE="$base_ref" IMAGE_REPOSITORY="$IMAGE_REPOSITORY" APP_IMAGE_TAG="$next_app_tag" \
  docker compose -f "${REPO_ROOT}/docker-compose.build.yml" push
release_phase_end

release_phase_start "read database migration head"
db_heads="$(docker run --rm --entrypoint alembic "$api_image" heads | awk '/\(head\)/ {print $1}')"
head_count="$(printf '%s\n' "$db_heads" | sed '/^$/d' | wc -l | tr -d ' ')"
test "$head_count" = "1" || fail "Release requires exactly one Alembic head; found ${head_count}."
db_revision="$db_heads"
release_log "Database revision=${db_revision}"
release_phase_end

release_phase_start "verify source and origin did not change"
source_sha="$(git -C "$REPO_ROOT" rev-parse source/main)"

git -C "$REPO_ROOT" fetch origin main
test "$(git -C "$REPO_ROOT" rev-parse origin/main)" = "$origin_release_sha" || \
  fail "origin/main changed during build; images are published but no release commit was created. Rebase and create a new release tag."
release_phase_end

release_phase_start "write release metadata"
tmp_release="$(mktemp "${REPO_ROOT}/.release.env.XXXXXX")"
printf '%s\n' \
  '# Immutable release state. Generated by make release; do not add secrets.' \
  "IMAGE_REPOSITORY=${IMAGE_REPOSITORY}" \
  "APP_IMAGE_TAG=${next_app_tag}" \
  "BASE_IMAGE_TAG=${next_base_tag}" \
  "BASE_INPUT_SHA=${next_base_sha}" \
  "SOURCE_SHA=${source_sha}" \
  "DB_REVISION=${db_revision}" > "$tmp_release"
mv "$tmp_release" "$RELEASE_FILE"
release_phase_end

release_phase_start "commit and push release metadata"
git -C "$REPO_ROOT" add release.env
git -C "$REPO_ROOT" commit -m "chore(release): ${next_app_tag}"
git -C "$REPO_ROOT" push origin main
release_phase_end

echo "Published release ${next_app_tag}. GitLab deploy pipeline may now pull immutable images."
