#!/usr/bin/env bash

set -euo pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${script_dir}/common.sh"

"${script_dir}/release-check.sh"
load_release_file

origin_release_sha="$(git -C "$REPO_ROOT" rev-parse origin/main)"
next_app_tag="$(bump_app_patch "$APP_IMAGE_TAG")"
next_base_tag="$BASE_IMAGE_TAG"
next_base_sha="$(base_input_sha)"
base_ref="${IMAGE_REPOSITORY}/base-ml:${BASE_IMAGE_TAG}"
api_image="${IMAGE_REPOSITORY}/api:${next_app_tag}"

if docker manifest inspect "$api_image" >/dev/null 2>&1; then
  fail "Refusing to overwrite immutable release image already present in registry: ${api_image}"
fi

if test "$next_base_sha" != "$BASE_INPUT_SHA"; then
  next_base_tag="$(bump_base_minor "$BASE_IMAGE_TAG")"
  next_base_ref="${IMAGE_REPOSITORY}/base-ml:${next_base_tag}"
  if docker manifest inspect "$next_base_ref" >/dev/null 2>&1; then
    fail "Refusing to overwrite immutable base image already present in registry: ${next_base_ref}"
  fi
  echo "Base inputs changed; publishing ${next_base_ref}"
  docker pull "$base_ref" || true
  docker build --cache-from "$base_ref" -t "$next_base_ref" -f "$BASE_DOCKERFILE" "$REPO_ROOT"
  docker push "$next_base_ref"
  base_ref="$next_base_ref"
else
  echo "Base inputs unchanged; pulling ${base_ref}"
  docker pull "$base_ref"
fi

echo "Building service images with ${base_ref} and tag ${next_app_tag}"
BASE_IMAGE="$base_ref" IMAGE_REPOSITORY="$IMAGE_REPOSITORY" APP_IMAGE_TAG="$next_app_tag" \
  docker compose -f "${REPO_ROOT}/docker-compose.build.yml" build
BASE_IMAGE="$base_ref" IMAGE_REPOSITORY="$IMAGE_REPOSITORY" APP_IMAGE_TAG="$next_app_tag" \
  docker compose -f "${REPO_ROOT}/docker-compose.build.yml" push

db_heads="$(docker run --rm --entrypoint alembic "$api_image" heads | awk '/\(head\)/ {print $1}')"
head_count="$(printf '%s\n' "$db_heads" | sed '/^$/d' | wc -l | tr -d ' ')"
test "$head_count" = "1" || fail "Release requires exactly one Alembic head; found ${head_count}."
db_revision="$db_heads"
source_sha="$(git -C "$REPO_ROOT" rev-parse HEAD)"

git -C "$REPO_ROOT" fetch origin main
test "$(git -C "$REPO_ROOT" rev-parse origin/main)" = "$origin_release_sha" || \
  fail "origin/main changed during build; images are published but no release commit was created. Rebase and create a new release tag."

tmp_release="$(mktemp "${REPO_ROOT}/.release.env.XXXXXX")"
printf '%s\n' \
  '# Immutable release state. Generated by make release; do not add secrets.' \
  "IMAGE_REPOSITORY=${IMAGE_REPOSITORY}" \
  "APP_IMAGE_TAG=${next_app_tag}" \
  "BASE_IMAGE_TAG=${next_base_tag}" \
  "BASE_INPUT_SHA=${next_base_sha}" \
  "SOURCE_SHA=${source_sha}" \
  "DB_REVISION=${db_revision}" > "$tmp_release"
mv "$tmp_release" "$RELEASE_FILE"

git -C "$REPO_ROOT" add release.env
git -C "$REPO_ROOT" commit -m "chore(release): ${next_app_tag}"
git -C "$REPO_ROOT" push origin main

echo "Published release ${next_app_tag}. GitLab deploy pipeline may now pull immutable images."
