"""
File List Tool — lists all files in the current chat (uploaded or generated).

Useful for the agent to inspect what files are available before reading or
referencing them.
"""
from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Optional

from sqlalchemy import select, and_

from app.agents.context import ToolContext, ToolResult
from app.agents.handlers.versioned_tool import VersionedTool, register_tool, tool_version
from app.core.db import get_session_factory
from app.core.logging import get_logger
from app.models.chat_attachment import ChatAttachment
from app.services.file_delivery_service import FileDeliveryService

logger = get_logger(__name__)

_INPUT_SCHEMA_V1 = {
    "type": "object",
    "properties": {
        "status": {
            "type": "string",
            "description": "Optional filter by status: 'uploaded', 'generated', or omit for all.",
            "enum": ["uploaded", "generated"],
        },
    },
}

_OUTPUT_SCHEMA_V1 = {
    "type": "object",
    "properties": {
        "files": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "file_id": {"type": "string"},
                    "file_name": {"type": "string"},
                    "content_type": {"type": "string"},
                    "size_bytes": {"type": "integer"},
                    "status": {"type": "string"},
                    "created_at": {"type": "string"},
                },
            },
        },
        "count": {"type": "integer"},
    },
}


@register_tool
class FileListTool(VersionedTool):
    """
    List all files in the current chat.

    Use this to discover what files were uploaded by the user or generated
    by the agent, before attempting to read or reference them.
    """

    tool_slug: ClassVar[str] = "file.list"
    domains: ClassVar[list] = ["system"]
    name: ClassVar[str] = "List Files"
    description: ClassVar[str] = (
        "List all files available in the current chat: uploaded by the user or generated by the agent. "
        "Returns file metadata including file_id, name, size, and status."
    )

    @tool_version(
        version="1.0.0",
        input_schema=_INPUT_SCHEMA_V1,
        output_schema=_OUTPUT_SCHEMA_V1,
        description="List chat attachments with optional status filter",
    )
    async def v1_0_0(self, ctx: ToolContext, args: Dict[str, Any]) -> ToolResult:
        import uuid as _uuid

        log = ctx.tool_logger("file.list")

        chat_id = ctx.chat_id
        user_id = ctx.user_id
        if not chat_id or not user_id:
            log.error("Missing chat_id or user_id in tool context")
            return ToolResult.fail(
                "File list requires a chat context.",
                logs=log.entries_dict(),
            )

        status_filter: Optional[str] = str(args.get("status") or "").strip().lower() or None
        if status_filter and status_filter not in ("uploaded", "generated"):
            return ToolResult.fail(
                f"Invalid status filter '{status_filter}'. Use 'uploaded', 'generated', or omit.",
                logs=log.entries_dict(),
            )

        log.info("Listing files", chat_id=str(chat_id), status_filter=status_filter)

        try:
            session_factory = get_session_factory()
            async with session_factory() as session:
                conditions = [
                    ChatAttachment.chat_id == chat_id,
                    ChatAttachment.owner_id == user_id,
                ]
                if status_filter:
                    conditions.append(ChatAttachment.status == status_filter)

                stmt = select(ChatAttachment).where(and_(*conditions)).order_by(ChatAttachment.created_at.desc())
                result = await session.execute(stmt)
                rows = list(result.scalars().all())

                files: List[Dict[str, Any]] = []
                for row in rows:
                    files.append({
                        "file_id": FileDeliveryService.make_chat_attachment_file_id(str(row.id)),
                        "file_name": row.file_name,
                        "content_type": row.content_type or "application/octet-stream",
                        "size_bytes": row.size_bytes,
                        "status": row.status,
                        "created_at": row.created_at.isoformat() if row.created_at else None,
                    })

                log.info("Files listed", count=len(files), chat_id=str(chat_id))
                return ToolResult.ok(
                    data={"files": files, "count": len(files)},
                    message=f"Found {len(files)} file(s) in this chat.",
                    logs=log.entries_dict(),
                )
        except Exception as exc:
            logger.error("File list failed: %s", exc, exc_info=True)
            log.error("File list failed", error=str(exc))
            return ToolResult.fail(
                f"Failed to list files: {exc}",
                logs=log.entries_dict(),
            )
