"""
File Read Tool — reads a file by its file_id from chat storage or document collections.

The agent can read:
- Chat attachments (chatatt_<uuid>) — uploaded by user or generated by the agent.
- Collection documents (ragdoc_<uuid>_original) — original files from a document collection.
- Collection exports (colexp_<uuid>) — CSV/JSONL exports generated by the agent.

Returns file content as text for supported text formats, or base64 for binary files.
"""
from __future__ import annotations

import base64
import re
from typing import Any, ClassVar, Dict

from app.agents.context import ToolContext, ToolResult
from app.agents.handlers.versioned_tool import VersionedTool, register_tool, tool_version
from app.core.logging import get_logger

logger = get_logger(__name__)

_TEXT_EXTENSIONS = {"txt", "md", "csv", "tsv", "json", "yaml", "yml", "log", "sql", "xml", "html"}
_MAX_READ_BYTES = 2 * 1024 * 1024

_FILE_ID_RE = re.compile(
    r"^(?:chatatt_([0-9a-fA-F-]{36})|ragdoc_([0-9a-fA-F-]{36})_(original|canonical)|colexp_([0-9a-fA-F-]{36}))$"
)

_INPUT_SCHEMA_V1 = {
    "type": "object",
    "properties": {
        "file_id": {
            "type": "string",
            "description": (
                "File ID to read. Supported formats: "
                "'chatatt_<uuid>' (chat attachment), "
                "'ragdoc_<uuid>_original' (document collection file), "
                "'colexp_<uuid>' (collection export). "
                "For collection documents, obtain file_id from collection.list_documents or collection.get_document."
            ),
        },
    },
    "required": ["file_id"],
}

_OUTPUT_SCHEMA_V1 = {
    "type": "object",
    "properties": {
        "file_id": {"type": "string"},
        "file_name": {"type": "string"},
        "content_type": {"type": "string"},
        "size_bytes": {"type": "integer"},
        "content": {"type": "string", "description": "Text content or base64-encoded binary"},
        "encoding": {"type": "string", "description": "'text' or 'base64'"},
    },
}


@register_tool
class FileReadTool(VersionedTool):
    """
    Read a file by its file_id from chat storage or document collections.

    Use this to inspect the contents of a previously uploaded/generated chat file,
    or to read an original file from a document collection (e.g. an Excel template).
    """

    tool_slug: ClassVar[str] = "file.read"
    domains: ClassVar[list] = ["system"]
    name: ClassVar[str] = "Read File"
    description: ClassVar[str] = (
        "Read a file by its file_id. Supports chat attachments (chatatt_<uuid>), "
        "document collection files (ragdoc_<uuid>_original), and collection exports (colexp_<uuid>). "
        "Returns text content for text files, or base64 for binary files. "
        "Use collection.get_document to obtain the file_id for a collection document."
    )

    @tool_version(
        version="1.0.0",
        input_schema=_INPUT_SCHEMA_V1,
        output_schema=_OUTPUT_SCHEMA_V1,
        description="Read file from S3/MinIO and return its contents",
    )
    async def v1_0_0(self, ctx: ToolContext, args: Dict[str, Any]) -> ToolResult:
        from app.adapters.s3_client import s3_manager
        from app.core.db import get_session_factory
        from app.repositories.factory import AsyncRepositoryFactory
        from app.services.file_delivery_service import FileDeliveryService

        log = ctx.tool_logger("file.read")

        file_id = str(args.get("file_id") or "").strip()
        if not file_id:
            log.error("Missing file_id")
            return ToolResult.fail("Missing 'file_id' argument", logs=log.entries_dict())

        if not _FILE_ID_RE.match(file_id):
            log.error("Invalid file_id format", file_id=file_id)
            return ToolResult.fail(
                f"Invalid file_id format '{file_id}'. "
                f"Expected 'chatatt_<uuid>', 'ragdoc_<uuid>_original', or 'colexp_<uuid>'.",
                logs=log.entries_dict(),
            )

        user_id = ctx.user_id
        if not user_id:
            log.error("Missing user_id in tool context")
            return ToolResult.fail(
                "File read requires a user context.",
                logs=log.entries_dict(),
            )

        log.info("Reading file", file_id=file_id)

        try:
            session_factory = get_session_factory()
            async with session_factory() as session:
                repo_factory = AsyncRepositoryFactory(
                    session, tenant_id=ctx.tenant_id, user_id=user_id
                )
                service = FileDeliveryService(session, repo_factory)
                resolved = await service.resolve(file_id, owner_id=str(user_id))

                # Load from S3
                payload = await s3_manager.get_object(resolved.bucket, resolved.key)
                if payload is None:
                    log.error("Failed to load file from storage", file_id=file_id)
                    return ToolResult.fail(
                        f"File '{file_id}' exists in database but could not be loaded from storage.",
                        logs=log.entries_dict(),
                    )

                size_bytes = len(payload)
                if size_bytes > _MAX_READ_BYTES:
                    log.error(
                        "File too large",
                        size_bytes=size_bytes,
                        max_bytes=_MAX_READ_BYTES,
                    )
                    return ToolResult.fail(
                        f"File size ({size_bytes} bytes) exceeds read limit of {_MAX_READ_BYTES} bytes. "
                        "Consider asking the user to provide a smaller file.",
                        logs=log.entries_dict(),
                    )

                ext = ""
                if resolved.file_name and "." in resolved.file_name:
                    ext = resolved.file_name.rsplit(".", 1)[-1].strip().lower()
                is_text = ext in _TEXT_EXTENSIONS

                if is_text:
                    try:
                        content = payload.decode("utf-8")
                        encoding = "text"
                    except UnicodeDecodeError:
                        content = base64.b64encode(payload).decode("ascii")
                        encoding = "base64"
                        is_text = False
                else:
                    content = base64.b64encode(payload).decode("ascii")
                    encoding = "base64"

                log.info(
                    "File read OK",
                    file_id=file_id,
                    file_name=resolved.file_name,
                    size_bytes=size_bytes,
                    encoding=encoding,
                )
                return ToolResult.ok(
                    data={
                        "file_id": file_id,
                        "file_name": resolved.file_name,
                        "content_type": resolved.content_type or "application/octet-stream",
                        "size_bytes": size_bytes,
                        "content": content,
                        "encoding": encoding,
                    },
                    message=f"File '{resolved.file_name}' read successfully ({encoding}, {size_bytes} bytes).",
                    logs=log.entries_dict(),
                )
        except Exception as exc:
            logger.error("File read failed: %s", exc, exc_info=True)
            log.error("File read failed", error=str(exc))
            return ToolResult.fail(
                f"Failed to read file: {exc}",
                logs=log.entries_dict(),
            )
