from typing import Protocol, Sequence

class EmbeddingsClient(Protocol):
    async def embed_texts(self, texts: Sequence[str], model: str = "default") -> list[list[float]]: ...
    async def embed_query(self, query: str, model: str = "default") -> list[float]: ...
