from typing import Protocol, Any, AsyncIterator, Mapping, Optional

class LLMClient(Protocol):
    async def chat(self, messages: list[Mapping[str, str]], *, params: Optional[dict] = None) -> dict: ...
    async def chat_stream(self, messages: list[Mapping[str, str]], *, params: Optional[dict] = None) -> AsyncIterator[str]: ...
