from typing import Protocol, BinaryIO

class ObjectStorage(Protocol):
    async def put(self, bucket: str, key: str, data: bytes, *, content_type: str | None = None) -> None: ...
    async def get(self, bucket: str, key: str) -> bytes: ...
    async def delete(self, bucket: str, key: str) -> None: ...
    async def presign_get(self, bucket: str, key: str, expires_in: int = 3600) -> str: ...
