"""Initial migration

Revision ID: 7ac97d34b0aa
Revises: 
Create Date: 2026-04-11 18:18:17.499624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ac97d34b0aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('allowed_collection_ids', postgresql.ARRAY(sa.UUID()), nullable=True, comment='Whitelist of Collection IDs bound to this agent container. NULL = all collections allowed by RBAC.'),
    sa.Column('logging_level', sa.String(length=10), server_default='brief', nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True, comment='Default model fallback for this agent container (AgentVersion.model -> Agent.model -> orchestration default)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_current_version_id'), 'agents', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('rate_limit_rph', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('ix_api_keys_tenant_id', 'api_keys', ['tenant_id'], unique=False)
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.String(length=50), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('collection_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('semantic_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_context_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'version', name='uq_collection_version')
    )
    op.create_index(op.f('ix_collection_versions_collection_id'), 'collection_versions', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_versions_status'), 'collection_versions', ['status'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('collection_type', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('vector_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qdrant_collection_name', sa.String(length=200), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('vectorized_rows', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('primary_key_field', sa.String(length=100), nullable=True),
    sa.Column('time_column', sa.String(length=100), nullable=True),
    sa.Column('default_sort', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('allow_unfiltered_search', sa.Boolean(), nullable=True),
    sa.Column('max_limit', sa.Integer(), nullable=True),
    sa.Column('query_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('data_instance_id', sa.UUID(), nullable=True),
    sa.Column('discovered_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Table schema / discovered SQL shape'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last schema sync timestamp for remote collections'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_current_version_id'), 'collections', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_collections_tenant_id'), 'collections', ['tenant_id'], unique=False)
    op.create_table('events_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False, comment='Sequential number for ordering (BIGSERIAL)'),
    sa.Column('type', sa.String(length=100), nullable=False, comment='rag.status|rag.embed.progress|rag.tags.updated|rag.deleted'),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Event payload'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when event was delivered to at least one SSE client'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index('ix_events_outbox_created_at', 'events_outbox', ['created_at'], unique=False)
    op.create_index('ix_events_outbox_delivered_at', 'events_outbox', ['delivered_at'], unique=False)
    op.create_index('ix_events_outbox_delivered_created', 'events_outbox', ['delivered_at', 'created_at'], unique=False)
    op.create_index('ix_events_outbox_seq', 'events_outbox', ['seq'], unique=False)
    op.create_index('ix_events_outbox_type', 'events_outbox', ['type'], unique=False)
    op.create_table('limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_limits_current_version_id'), 'limits', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_limits_slug'), 'limits', ['slug'], unique=True)
    op.create_table('orchestration_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('executor_model', sa.String(length=100), nullable=True, comment='Default model alias for execution/generation'),
    sa.Column('executor_temperature', sa.Float(), nullable=True),
    sa.Column('executor_timeout_s', sa.Integer(), nullable=True, comment='Default timeout for executor in seconds'),
    sa.Column('executor_max_steps', sa.Integer(), nullable=True, comment='Default max planner loop iterations'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True, comment='Associated agent run (optional)'),
    sa.Column('chat_id', sa.UUID(), nullable=True, comment='Associated chat session (optional)'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant ID for multi-tenancy'),
    sa.Column('planner_trace_id', sa.UUID(), nullable=True, comment='Link to system LLM trace that created this plan'),
    sa.Column('planner_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of PlannerInput at plan creation'),
    sa.Column('goal_source', sa.String(length=50), nullable=True, comment='Where the goal came from: user_message|triage_goal|resume'),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Plan structure with steps and metadata'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Plan status: draft | active | completed | failed | paused'),
    sa.Column('current_step', sa.Integer(), nullable=False, comment='Current step index for resume functionality'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Plan creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Plan last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_agent_run_id'), 'plans', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_plans_chat_id'), 'plans', ['chat_id'], unique=False)
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_plans_planner_trace_id'), 'plans', ['planner_trace_id'], unique=False)
    op.create_index(op.f('ix_plans_status'), 'plans', ['status'], unique=False)
    op.create_index(op.f('ix_plans_tenant_id'), 'plans', ['tenant_id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policies_text', sa.Text(), nullable=True),
    sa.Column('require_confirmation_for_write', sa.Boolean(), nullable=True),
    sa.Column('require_confirmation_for_destructive', sa.Boolean(), nullable=True),
    sa.Column('forbid_destructive', sa.Boolean(), nullable=True),
    sa.Column('forbid_write_in_prod', sa.Boolean(), nullable=True),
    sa.Column('require_backup_before_write', sa.Boolean(), nullable=True),
    sa.Column('abs_max_timeout_s', sa.Integer(), nullable=True),
    sa.Column('abs_max_retries', sa.Integer(), nullable=True),
    sa.Column('abs_max_steps', sa.Integer(), nullable=True),
    sa.Column('abs_max_plan_steps', sa.Integer(), nullable=True),
    sa.Column('abs_max_concurrency', sa.Integer(), nullable=True),
    sa.Column('abs_max_task_runtime_s', sa.Integer(), nullable=True),
    sa.Column('abs_max_tool_calls_per_step', sa.Integer(), nullable=True),
    sa.Column('chat_upload_max_bytes', sa.Integer(), nullable=True),
    sa.Column('chat_upload_allowed_extensions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_current_version_id'), 'policies', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_policies_slug'), 'policies', ['slug'], unique=True)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('recommended_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_recommended_version_id'), 'prompts', ['recommended_version_id'], unique=False)
    op.create_index(op.f('ix_prompts_slug'), 'prompts', ['slug'], unique=True)
    op.create_table('sandbox_branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('parent_branch_id', sa.UUID(), nullable=True),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_branches_parent_branch_id', 'sandbox_branches', ['parent_branch_id'], unique=False)
    op.create_index('ix_sandbox_branches_parent_run_id', 'sandbox_branches', ['parent_run_id'], unique=False)
    op.create_index('ix_sandbox_branches_session_id', 'sandbox_branches', ['session_id'], unique=False)
    op.create_table('sandbox_override_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_override_snapshots_branch_id', 'sandbox_override_snapshots', ['branch_id'], unique=False)
    op.create_index('ix_sandbox_override_snapshots_hash', 'sandbox_override_snapshots', ['snapshot_hash'], unique=False)
    op.create_index('ix_sandbox_override_snapshots_session_id', 'sandbox_override_snapshots', ['session_id'], unique=False)
    op.create_table('sandbox_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('paused_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paused_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_runs_branch_id', 'sandbox_runs', ['branch_id'], unique=False)
    op.create_index('ix_sandbox_runs_session_id', 'sandbox_runs', ['session_id'], unique=False)
    op.create_index('ix_sandbox_runs_snapshot_id', 'sandbox_runs', ['snapshot_id'], unique=False)
    op.create_table('system_llm_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False, comment='Role type: triage | planner | summary'),
    sa.Column('identity', sa.Text(), nullable=True, comment='Role identity description'),
    sa.Column('mission', sa.Text(), nullable=True, comment='Role mission and purpose'),
    sa.Column('rules', sa.Text(), nullable=True, comment='Core rules and guidelines'),
    sa.Column('safety', sa.Text(), nullable=True, comment='Safety constraints and rules'),
    sa.Column('output_requirements', sa.Text(), nullable=True, comment='Output format and structure requirements'),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Few-shot examples for the role'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='Model alias for this role'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='Temperature for LLM calls'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='Maximum tokens for LLM response'),
    sa.Column('timeout_s', sa.Integer(), nullable=True, comment='Timeout in seconds'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='Maximum retry attempts'),
    sa.Column('retry_backoff', sa.String(length=10), nullable=True, comment='Retry backoff strategy: none | linear | exp'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether this role configuration is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_backend_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('deprecation_message', sa.Text(), nullable=True),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('worker_build_id', sa.String(length=100), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'version', name='uq_tool_backend_release_version')
    )
    op.create_index(op.f('ix_tool_backend_releases_tool_id'), 'tool_backend_releases', ['tool_id'], unique=False)
    op.create_table('tool_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instance_kind', sa.String(length=20), server_default='data', nullable=False, comment='Instance role: data | service'),
    sa.Column('connector_type', sa.String(length=20), server_default='data', nullable=False, comment='Connector type: data | mcp | model'),
    sa.Column('connector_subtype', sa.String(length=20), nullable=True, comment='Data connector subtype: sql | api'),
    sa.Column('placement', sa.String(length=20), server_default='remote', nullable=False, comment='Operational model: local | remote'),
    sa.Column('domain', sa.String(length=50), server_default='rag', nullable=False, comment='Transitional classification tag: llm, mcp, collection.document, jira, etc.'),
    sa.Column('url', sa.Text(), server_default='', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('access_via_instance_id', sa.UUID(), nullable=True, comment='Service instance used to access this data instance'),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("connector_subtype IS NULL OR connector_subtype IN ('sql', 'api')", name='ck_connector_subtype'),
    sa.CheckConstraint("connector_type IN ('data', 'mcp', 'model')", name='ck_connector_type'),
    sa.CheckConstraint("instance_kind IN ('data', 'service')", name='ck_instance_kind'),
    sa.CheckConstraint("placement IN ('local', 'remote')", name='ck_instance_placement'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_tool_instance_slug')
    )
    op.create_index(op.f('ix_tool_instances_access_via_instance_id'), 'tool_instances', ['access_via_instance_id'], unique=False)
    op.create_index(op.f('ix_tool_instances_slug'), 'tool_instances', ['slug'], unique=False)
    op.create_table('tool_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('backend_release_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('semantic_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_hash', sa.String(length=64), nullable=True),
    sa.Column('expected_schema_hash', sa.String(length=64), nullable=True),
    sa.Column('parent_release_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'version', name='uq_tool_release_version')
    )
    op.create_index(op.f('ix_tool_releases_backend_release_id'), 'tool_releases', ['backend_release_id'], unique=False)
    op.create_index(op.f('ix_tool_releases_status'), 'tool_releases', ['status'], unique=False)
    op.create_index(op.f('ix_tool_releases_tool_id'), 'tool_releases', ['tool_id'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domains', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False, comment='Runtime domains / tags used for grouping and routing'),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_current_version_id'), 'tools', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_tools_slug'), 'tools', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='reader', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('require_password_change', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('identity', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('tool_use_rules', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('timeout_s', sa.Integer(), nullable=True),
    sa.Column('max_steps', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('requires_confirmation_for_write', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('never_do', sa.Text(), nullable=True),
    sa.Column('allowed_ops', sa.Text(), nullable=True),
    sa.Column('short_info', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_routable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('routing_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('routing_negative_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uix_agent_version')
    )
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_versions_status'), 'agent_versions', ['status'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('token_prefix', sa.String(length=10), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('collection_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_contract', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='External schema contract snapshot (e.g. remote SQL DDL / discovered source contract)'),
    sa.Column('schema_status', sa.String(length=20), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_schemas_collection_id'), 'collection_schemas', ['collection_id'], unique=True)
    op.create_table('discovered_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False, comment="Tool slug (e.g. 'collection.search', 'jira.issues.list')"),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_id', sa.UUID(), nullable=True, comment='Optional publication container link. NULL means discovered but unpublished.'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='local | mcp'),
    sa.Column('provider_instance_id', sa.UUID(), nullable=True, comment='MCP provider ToolInstance (NULL for local tools)'),
    sa.Column('domains', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False, comment="Business domains this tool serves (e.g. ['collection.table', 'rag'])"),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON Schema for input parameters'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON Schema for output'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False if tool disappeared on last rescan'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='When tool was last seen during scan'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_tools_provider_instance_id'), 'discovered_tools', ['provider_instance_id'], unique=False)
    op.create_index(op.f('ix_discovered_tools_slug'), 'discovered_tools', ['slug'], unique=False)
    op.create_index(op.f('ix_discovered_tools_tool_id'), 'discovered_tools', ['tool_id'], unique=False)
    op.create_index('uq_discovered_local_slug_null_provider', 'discovered_tools', ['slug'], unique=True, postgresql_where=sa.text('provider_instance_id IS NULL'))
    op.create_index('uq_discovered_slug_provider', 'discovered_tools', ['slug', 'provider_instance_id'], unique=True, postgresql_where=sa.text('provider_instance_id IS NOT NULL'))
    op.create_table('limit_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('limit_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=True),
    sa.Column('max_tool_calls', sa.Integer(), nullable=True),
    sa.Column('max_wall_time_ms', sa.Integer(), nullable=True),
    sa.Column('tool_timeout_ms', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('limit_id', 'version', name='uix_limit_version')
    )
    op.create_index(op.f('ix_limit_versions_limit_id'), 'limit_versions', ['limit_id'], unique=False)
    op.create_index(op.f('ix_limit_versions_status'), 'limit_versions', ['status'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False, comment='Unique identifier (e.g. llm.chat.default)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable name'),
    sa.Column('type', sa.Enum('LLM_CHAT', 'EMBEDDING', 'RERANKER', 'OCR', 'ASR', 'TTS', name='model_type'), nullable=False, comment='Model type'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Deprecated provider label (openai, groq, local, etc.)'),
    sa.Column('connector', sa.String(length=50), nullable=False, comment='Connection driver (openai_http, local_emb_http, local_rerank_http, etc.)'),
    sa.Column('provider_model_name', sa.String(length=255), nullable=False, comment='Model name at provider'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='Direct endpoint URL for local or standalone model connectors'),
    sa.Column('instance_id', sa.UUID(), nullable=True, comment='FK to tool_instances (provider connection)'),
    sa.Column('extra_config', sa.JSON(), nullable=True, comment='Provider-specific config (temperature, dimensions, etc.)'),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'DEPRECATED', 'MAINTENANCE', name='model_status'), nullable=False, comment='Availability status'),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='System model (cannot be deleted)'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Is model enabled'),
    sa.Column('default_for_type', sa.Boolean(), nullable=False, comment='Default model for this type'),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.Enum('HEALTHY', 'DEGRADED', 'UNAVAILABLE', name='health_status'), nullable=True),
    sa.Column('health_error', sa.Text(), nullable=True),
    sa.Column('health_latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='Model version (for tracking changes)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_alias'), 'models', ['alias'], unique=True)
    op.create_index(op.f('ix_models_connector'), 'models', ['connector'], unique=False)
    op.create_index(op.f('ix_models_instance_id'), 'models', ['instance_id'], unique=False)
    op.create_index(op.f('ix_models_type'), 'models', ['type'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('policy_text', sa.Text(), nullable=False),
    sa.Column('policy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uix_policy_version')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_status'), 'policy_versions', ['status'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('input_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'version', name='uix_prompt_version')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_id'), 'prompt_versions', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_status'), 'prompt_versions', ['status'], unique=False)
    op.create_table('sandbox_branch_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_branch_overrides_branch_id', 'sandbox_branch_overrides', ['branch_id'], unique=False)
    op.create_index('uq_sandbox_branch_overrides_key', 'sandbox_branch_overrides', ['branch_id', 'entity_type', 'entity_id', 'field_path'], unique=True)
    op.create_table('sandbox_run_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('step_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_run_steps_run_id', 'sandbox_run_steps', ['run_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding_model_alias', sa.String(length=100), nullable=True),
    sa.Column('chunk_profile', sa.String(length=50), nullable=True, comment='Default chunking profile (by_tokens, by_paragraphs, etc.)'),
    sa.Column('chunk_size', sa.Integer(), nullable=True, comment='Default chunk size in tokens'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True, comment='Default chunk overlap in tokens'),
    sa.Column('ocr', sa.Boolean(), nullable=False),
    sa.Column('layout', sa.Boolean(), nullable=False),
    sa.Column('default_agent_slug', sa.String(length=100), nullable=True, comment='Default agent slug for this tenant'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chats_tenant_created', 'chats', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_chats_tenant_id', 'chats', ['tenant_id'], unique=False)
    op.create_index('ix_chats_tenant_name', 'chats', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_chats_tenant_owner', 'chats', ['tenant_id', 'owner_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_tenant_id', sa.UUID(), nullable=True),
    sa.Column('owner_platform', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("auth_type IN ('token', 'basic', 'oauth', 'api_key')", name='ck_credential_auth_type'),
    sa.CheckConstraint('\n            (owner_platform::int +\n             (owner_user_id IS NOT NULL)::int +\n             (owner_tenant_id IS NOT NULL)::int) = 1\n            ', name='ck_credential_single_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credential_platform_lookup', 'credentials', ['owner_platform', 'instance_id'], unique=False, postgresql_where='is_active = true')
    op.create_index('ix_credential_tenant_lookup', 'credentials', ['owner_tenant_id', 'instance_id'], unique=False, postgresql_where='is_active = true')
    op.create_index('ix_credential_user_lookup', 'credentials', ['owner_user_id', 'instance_id'], unique=False, postgresql_where='is_active = true')
    op.create_index(op.f('ix_credentials_instance_id'), 'credentials', ['instance_id'], unique=False)
    op.create_table('ragdocuments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('uploaded', 'uploading', 'processing', 'processed', 'ready', 'failed', 'archived', 'queued', name='documentstatus'), server_default='uploaded', nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('source_mime', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('s3_key_raw', sa.String(length=500), nullable=True),
    sa.Column('s3_key_processed', sa.String(length=500), nullable=True),
    sa.Column('url_file', sa.Text(), nullable=True),
    sa.Column('url_canonical_file', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('global_version', sa.Integer(), nullable=True),
    sa.Column('date_upload', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agg_status', sa.String(length=20), nullable=True),
    sa.Column('agg_details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ragdocuments_scope', 'ragdocuments', ['scope'], unique=False)
    op.create_index('ix_ragdocuments_status', 'ragdocuments', ['status'], unique=False)
    op.create_index('ix_ragdocuments_tenant_id', 'ragdocuments', ['tenant_id'], unique=False)
    op.create_index('ix_ragdocuments_uploaded_by', 'ragdocuments', ['uploaded_by'], unique=False)
    op.create_table('rbac_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_tenant_id', sa.UUID(), nullable=True),
    sa.Column('owner_platform', sa.Boolean(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('effect', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("effect IN ('allow', 'deny')", name='ck_rbac_rule_effect'),
    sa.CheckConstraint("level IN ('platform', 'tenant', 'user')", name='ck_rbac_rule_level'),
    sa.CheckConstraint("resource_type IN ('agent', 'tool', 'instance', 'collection', 'operation')", name='ck_rbac_rule_resource_type'),
    sa.CheckConstraint('\n            (owner_platform::int +\n             (owner_user_id IS NOT NULL)::int +\n             (owner_tenant_id IS NOT NULL)::int) = 1\n            ', name='ck_rbac_rule_single_owner'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'owner_user_id', 'owner_tenant_id', 'owner_platform', 'resource_type', 'resource_id', name='uq_rbac_rule_owner_resource')
    )
    op.create_index('ix_rbac_rule_lookup', 'rbac_rules', ['level', 'resource_type', 'resource_id'], unique=False)
    op.create_index('ix_rbac_rule_owner_tenant', 'rbac_rules', ['owner_tenant_id'], unique=False, postgresql_where='owner_tenant_id IS NOT NULL')
    op.create_index('ix_rbac_rule_owner_user', 'rbac_rules', ['owner_user_id'], unique=False, postgresql_where='owner_user_id IS NOT NULL')
    op.create_index('ix_rbac_rule_resource', 'rbac_rules', ['resource_type', 'resource_id', 'effect'], unique=False)
    op.create_table('routing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('selected_agent_slug', sa.String(length=255), nullable=True),
    sa.Column('agent_confidence', sa.Float(), nullable=True),
    sa.Column('routing_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_collections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=True),
    sa.Column('effective_operations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_data_instances', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operation_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('routed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('routing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_logs_run_id'), 'routing_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_routing_logs_tenant_id'), 'routing_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_routing_logs_user_id'), 'routing_logs', ['user_id'], unique=False)
    op.create_table('sandbox_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ttl_days', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_sessions_owner_id', 'sandbox_sessions', ['owner_id'], unique=False)
    op.create_index('ix_sandbox_sessions_status_expires', 'sandbox_sessions', ['status', 'expires_at'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index('ix_sources_tenant_id', 'sources', ['tenant_id'], unique=False)
    op.create_index('ix_sources_updated_at', 'sources', ['updated_at'], unique=False)
    op.create_table('user_tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.UUID(), nullable=True),
    sa.Column('summary_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_summaries_chat_id'), 'chat_summaries', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_summaries_tenant_id'), 'chat_summaries', ['tenant_id'], unique=False)
    op.create_table('chatmessages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'tool', name='chat_role_enum'), nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('message_type', sa.String(length=50), server_default='text', nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatmessages_chat_id_created_at', 'chatmessages', ['chat_id', 'created_at'], unique=False)
    op.create_index('ix_chatmessages_tenant_chat', 'chatmessages', ['tenant_id', 'chat_id'], unique=False)
    op.create_index('ix_chatmessages_tenant_created', 'chatmessages', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_chatmessages_tenant_id', 'chatmessages', ['tenant_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('source_id', 'offset', name='uq_chunks_source_offset')
    )
    op.create_index('ix_chunks_hash', 'chunks', ['hash'], unique=False)
    op.create_index('ix_chunks_source_id', 'chunks', ['source_id'], unique=False)
    op.create_table('emb_status',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('model_alias', sa.Text(), nullable=False),
    sa.Column('done_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'model_alias')
    )
    op.create_index('ix_emb_status_model_alias', 'emb_status', ['model_alias'], unique=False)
    op.create_index('ix_emb_status_source_id', 'emb_status', ['source_id'], unique=False)
    op.create_table('execution_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('dialogue_summary', sa.Text(), nullable=True),
    sa.Column('current_phase_id', sa.String(length=128), nullable=True),
    sa.Column('current_agent_slug', sa.String(length=255), nullable=True),
    sa.Column('step_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('open_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loop_signatures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memory_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_status', sa.String(length=32), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('final_error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_memories_chat_id'), 'execution_memories', ['chat_id'], unique=False)
    op.create_index(op.f('ix_execution_memories_run_id'), 'execution_memories', ['run_id'], unique=True)
    op.create_index(op.f('ix_execution_memories_tenant_id'), 'execution_memories', ['tenant_id'], unique=False)
    op.create_table('rag_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('node_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('celery_task_id', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('modality', sa.String(length=20), nullable=True),
    sa.Column('error_short', sa.Text(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'node_type', 'node_key', name='uq_rag_statuses_doc_node')
    )
    op.create_index('ix_rag_statuses_doc_id', 'rag_statuses', ['doc_id'], unique=False)
    op.create_index('ix_rag_statuses_node_type', 'rag_statuses', ['node_type'], unique=False)
    op.create_index('ix_rag_statuses_status', 'rag_statuses', ['status'], unique=False)
    op.create_index('ix_rag_statuses_updated_at', 'rag_statuses', ['updated_at'], unique=False)
    op.create_table('ragchunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_idx', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_version', sa.String(length=255), nullable=True),
    sa.Column('date_embedding', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.String(), nullable=True),
    sa.Column('qdrant_point_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ragchunks_document_id', 'ragchunks', ['document_id'], unique=False)
    op.create_index('ix_ragchunks_document_idx', 'ragchunks', ['document_id', 'chunk_idx'], unique=False)
    op.create_table('sandbox_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_overrides_entity', 'sandbox_overrides', ['session_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_sandbox_overrides_session_id', 'sandbox_overrides', ['session_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_slug', sa.String(length=255), nullable=False),
    sa.Column('logging_level', sa.String(length=10), server_default='brief', nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('total_llm_calls', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('paused_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paused_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_slug'), 'agent_runs', ['agent_slug'], unique=False)
    op.create_table('chat_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_ext', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_bucket', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='uploaded', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_attachments_chat_id', 'chat_attachments', ['chat_id'], unique=False)
    op.create_index('ix_chat_attachments_message_id', 'chat_attachments', ['message_id'], unique=False)
    op.create_index('ix_chat_attachments_owner_id', 'chat_attachments', ['owner_id'], unique=False)
    op.create_index('ix_chat_attachments_tenant_id', 'chat_attachments', ['tenant_id'], unique=False)
    op.create_table('agent_run_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_steps_step_type'), 'agent_run_steps', ['step_type'], unique=False)
    op.create_table('chat_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('user_message_id', sa.UUID(), nullable=True),
    sa.Column('assistant_message_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='started', nullable=False),
    sa.Column('pause_status', sa.String(length=50), nullable=True),
    sa.Column('paused_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paused_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_turns_chat_id_started_at', 'chat_turns', ['chat_id', 'started_at'], unique=False)
    op.create_index('ix_chat_turns_idempotency_key', 'chat_turns', ['idempotency_key'], unique=False)
    op.create_index('ix_chat_turns_pause_status', 'chat_turns', ['pause_status'], unique=False)
    op.create_index('ix_chat_turns_request_hash', 'chat_turns', ['request_hash'], unique=False)
    op.create_index('ix_chat_turns_tenant_id', 'chat_turns', ['tenant_id'], unique=False)
    op.create_index('ix_chat_turns_user_id', 'chat_turns', ['user_id'], unique=False)
    op.create_table('system_llm_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_type', sa.String(length=20), nullable=False, comment='triage | planner | summary'),
    sa.Column('chat_id', sa.UUID(), nullable=True, comment='Associated chat session (optional)'),
    sa.Column('agent_run_id', sa.UUID(), nullable=True, comment='Associated agent run (optional)'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who initiated the trace'),
    sa.Column('role_id', sa.UUID(), nullable=True, comment='SystemLLMRole used for this trace'),
    sa.Column('role_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Frozen snapshot of role configuration at execution time'),
    sa.Column('compiled_prompt', sa.Text(), nullable=False, comment='Final assembled prompt sent to LLM'),
    sa.Column('compiled_prompt_hash', sa.String(length=16), nullable=False, comment='SHA-256 hash of compiled prompt for deduplication'),
    sa.Column('structured_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete input (TriageInput/PlannerInput/SummaryInput)'),
    sa.Column('context_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional context variables (available_agents, tools, etc.)'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='LLM model used'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='Temperature setting'),
    sa.Column('max_tokens', sa.Integer(), nullable=False, comment='Max tokens setting'),
    sa.Column('messages_sent', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete messages array sent to LLM'),
    sa.Column('raw_response', sa.Text(), nullable=False, comment='Raw LLM response before parsing'),
    sa.Column('parsed_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Parsed response after JSON extraction'),
    sa.Column('validation_status', sa.String(length=50), nullable=False, comment='success | failed | fallback_applied'),
    sa.Column('validation_error', sa.Text(), nullable=True, comment='Validation error if any'),
    sa.Column('fallback_applied', sa.Boolean(), nullable=False, comment='Whether smart fallback mapping was applied'),
    sa.Column('fallback_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Details of fallback mapping if applied'),
    sa.Column('attempt_number', sa.Integer(), nullable=False, comment='Attempt number (1, 2, 3...)'),
    sa.Column('total_attempts', sa.Integer(), nullable=False, comment='Total attempts made'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='Duration of LLM call in milliseconds'),
    sa.Column('tokens_in', sa.Integer(), nullable=True, comment='Input tokens if available'),
    sa.Column('tokens_out', sa.Integer(), nullable=True, comment='Output tokens if available'),
    sa.Column('result_type', sa.String(length=50), nullable=True, comment='Result type (final|agent|plan|ask_user for triage, etc.)'),
    sa.Column('result_summary', sa.Text(), nullable=True, comment='Brief description of the result'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Trace creation timestamp'),
    sa.Column('error', sa.Text(), nullable=True, comment='Error if trace failed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_llm_traces_agent_run_id'), 'system_llm_traces', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_chat_id'), 'system_llm_traces', ['chat_id'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_compiled_prompt_hash'), 'system_llm_traces', ['compiled_prompt_hash'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_created_at'), 'system_llm_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_result_type'), 'system_llm_traces', ['result_type'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_role_id'), 'system_llm_traces', ['role_id'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_tenant_id'), 'system_llm_traces', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_trace_type'), 'system_llm_traces', ['trace_type'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_user_id'), 'system_llm_traces', ['user_id'], unique=False)
    op.create_index(op.f('ix_system_llm_traces_validation_status'), 'system_llm_traces', ['validation_status'], unique=False)
    # Foreign keys skipped for clean migration - add manually if needed

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_llm_traces_validation_status'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_user_id'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_trace_type'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_tenant_id'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_role_id'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_result_type'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_created_at'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_compiled_prompt_hash'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_chat_id'), table_name='system_llm_traces')
    op.drop_index(op.f('ix_system_llm_traces_agent_run_id'), table_name='system_llm_traces')
    op.drop_table('system_llm_traces')
    op.drop_index('ix_chat_turns_user_id', table_name='chat_turns')
    op.drop_index('ix_chat_turns_tenant_id', table_name='chat_turns')
    op.drop_index('ix_chat_turns_request_hash', table_name='chat_turns')
    op.drop_index('ix_chat_turns_pause_status', table_name='chat_turns')
    op.drop_index('ix_chat_turns_idempotency_key', table_name='chat_turns')
    op.drop_index('ix_chat_turns_chat_id_started_at', table_name='chat_turns')
    op.drop_table('chat_turns')
    op.drop_index(op.f('ix_agent_run_steps_step_type'), table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index('ix_chat_attachments_tenant_id', table_name='chat_attachments')
    op.drop_index('ix_chat_attachments_owner_id', table_name='chat_attachments')
    op.drop_index('ix_chat_attachments_message_id', table_name='chat_attachments')
    op.drop_index('ix_chat_attachments_chat_id', table_name='chat_attachments')
    op.drop_table('chat_attachments')
    op.drop_index(op.f('ix_agent_runs_agent_slug'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_sandbox_overrides_session_id', table_name='sandbox_overrides')
    op.drop_index('ix_sandbox_overrides_entity', table_name='sandbox_overrides')
    op.drop_table('sandbox_overrides')
    op.drop_index('ix_ragchunks_document_idx', table_name='ragchunks')
    op.drop_index('ix_ragchunks_document_id', table_name='ragchunks')
    op.drop_table('ragchunks')
    op.drop_index('ix_rag_statuses_updated_at', table_name='rag_statuses')
    op.drop_index('ix_rag_statuses_status', table_name='rag_statuses')
    op.drop_index('ix_rag_statuses_node_type', table_name='rag_statuses')
    op.drop_index('ix_rag_statuses_doc_id', table_name='rag_statuses')
    op.drop_table('rag_statuses')
    op.drop_index(op.f('ix_execution_memories_tenant_id'), table_name='execution_memories')
    op.drop_index(op.f('ix_execution_memories_run_id'), table_name='execution_memories')
    op.drop_index(op.f('ix_execution_memories_chat_id'), table_name='execution_memories')
    op.drop_table('execution_memories')
    op.drop_index('ix_emb_status_source_id', table_name='emb_status')
    op.drop_index('ix_emb_status_model_alias', table_name='emb_status')
    op.drop_table('emb_status')
    op.drop_index('ix_chunks_source_id', table_name='chunks')
    op.drop_index('ix_chunks_hash', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_chatmessages_tenant_id', table_name='chatmessages')
    op.drop_index('ix_chatmessages_tenant_created', table_name='chatmessages')
    op.drop_index('ix_chatmessages_tenant_chat', table_name='chatmessages')
    op.drop_index('ix_chatmessages_chat_id_created_at', table_name='chatmessages')
    op.drop_table('chatmessages')
    op.drop_index(op.f('ix_chat_summaries_tenant_id'), table_name='chat_summaries')
    op.drop_index(op.f('ix_chat_summaries_chat_id'), table_name='chat_summaries')
    op.drop_table('chat_summaries')
    op.drop_table('user_tenants')
    op.drop_index('ix_sources_updated_at', table_name='sources')
    op.drop_index('ix_sources_tenant_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_sandbox_sessions_status_expires', table_name='sandbox_sessions')
    op.drop_index('ix_sandbox_sessions_owner_id', table_name='sandbox_sessions')
    op.drop_table('sandbox_sessions')
    op.drop_index(op.f('ix_routing_logs_user_id'), table_name='routing_logs')
    op.drop_index(op.f('ix_routing_logs_tenant_id'), table_name='routing_logs')
    op.drop_index(op.f('ix_routing_logs_run_id'), table_name='routing_logs')
    op.drop_table('routing_logs')
    op.drop_index('ix_rbac_rule_resource', table_name='rbac_rules')
    op.drop_index('ix_rbac_rule_owner_user', table_name='rbac_rules', postgresql_where='owner_user_id IS NOT NULL')
    op.drop_index('ix_rbac_rule_owner_tenant', table_name='rbac_rules', postgresql_where='owner_tenant_id IS NOT NULL')
    op.drop_index('ix_rbac_rule_lookup', table_name='rbac_rules')
    op.drop_table('rbac_rules')
    op.drop_index('ix_ragdocuments_uploaded_by', table_name='ragdocuments')
    op.drop_index('ix_ragdocuments_tenant_id', table_name='ragdocuments')
    op.drop_index('ix_ragdocuments_status', table_name='ragdocuments')
    op.drop_index('ix_ragdocuments_scope', table_name='ragdocuments')
    op.drop_table('ragdocuments')
    op.drop_index(op.f('ix_credentials_instance_id'), table_name='credentials')
    op.drop_index('ix_credential_user_lookup', table_name='credentials', postgresql_where='is_active = true')
    op.drop_index('ix_credential_tenant_lookup', table_name='credentials', postgresql_where='is_active = true')
    op.drop_index('ix_credential_platform_lookup', table_name='credentials', postgresql_where='is_active = true')
    op.drop_table('credentials')
    op.drop_index('ix_chats_tenant_owner', table_name='chats')
    op.drop_index('ix_chats_tenant_name', table_name='chats')
    op.drop_index('ix_chats_tenant_id', table_name='chats')
    op.drop_index('ix_chats_tenant_created', table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_sandbox_run_steps_run_id', table_name='sandbox_run_steps')
    op.drop_table('sandbox_run_steps')
    op.drop_index('uq_sandbox_branch_overrides_key', table_name='sandbox_branch_overrides')
    op.drop_index('ix_sandbox_branch_overrides_branch_id', table_name='sandbox_branch_overrides')
    op.drop_table('sandbox_branch_overrides')
    op.drop_index(op.f('ix_prompt_versions_status'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_prompt_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_policy_versions_status'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_models_type'), table_name='models')
    op.drop_index(op.f('ix_models_instance_id'), table_name='models')
    op.drop_index(op.f('ix_models_connector'), table_name='models')
    op.drop_index(op.f('ix_models_alias'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_limit_versions_status'), table_name='limit_versions')
    op.drop_index(op.f('ix_limit_versions_limit_id'), table_name='limit_versions')
    op.drop_table('limit_versions')
    op.drop_index('uq_discovered_slug_provider', table_name='discovered_tools', postgresql_where=sa.text('provider_instance_id IS NOT NULL'))
    op.drop_index('uq_discovered_local_slug_null_provider', table_name='discovered_tools', postgresql_where=sa.text('provider_instance_id IS NULL'))
    op.drop_index(op.f('ix_discovered_tools_tool_id'), table_name='discovered_tools')
    op.drop_index(op.f('ix_discovered_tools_slug'), table_name='discovered_tools')
    op.drop_index(op.f('ix_discovered_tools_provider_instance_id'), table_name='discovered_tools')
    op.drop_table('discovered_tools')
    op.drop_index(op.f('ix_collection_schemas_collection_id'), table_name='collection_schemas')
    op.drop_table('collection_schemas')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_agent_versions_status'), table_name='agent_versions')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_slug'), table_name='tools')
    op.drop_index(op.f('ix_tools_current_version_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_tool_releases_tool_id'), table_name='tool_releases')
    op.drop_index(op.f('ix_tool_releases_status'), table_name='tool_releases')
    op.drop_index(op.f('ix_tool_releases_backend_release_id'), table_name='tool_releases')
    op.drop_table('tool_releases')
    op.drop_index(op.f('ix_tool_instances_slug'), table_name='tool_instances')
    op.drop_index(op.f('ix_tool_instances_access_via_instance_id'), table_name='tool_instances')
    op.drop_table('tool_instances')
    op.drop_index(op.f('ix_tool_backend_releases_tool_id'), table_name='tool_backend_releases')
    op.drop_table('tool_backend_releases')
    op.drop_table('system_llm_roles')
    op.drop_index('ix_sandbox_runs_snapshot_id', table_name='sandbox_runs')
    op.drop_index('ix_sandbox_runs_session_id', table_name='sandbox_runs')
    op.drop_index('ix_sandbox_runs_branch_id', table_name='sandbox_runs')
    op.drop_table('sandbox_runs')
    op.drop_index('ix_sandbox_override_snapshots_session_id', table_name='sandbox_override_snapshots')
    op.drop_index('ix_sandbox_override_snapshots_hash', table_name='sandbox_override_snapshots')
    op.drop_index('ix_sandbox_override_snapshots_branch_id', table_name='sandbox_override_snapshots')
    op.drop_table('sandbox_override_snapshots')
    op.drop_index('ix_sandbox_branches_session_id', table_name='sandbox_branches')
    op.drop_index('ix_sandbox_branches_parent_run_id', table_name='sandbox_branches')
    op.drop_index('ix_sandbox_branches_parent_branch_id', table_name='sandbox_branches')
    op.drop_table('sandbox_branches')
    op.drop_index(op.f('ix_prompts_slug'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_recommended_version_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_policies_slug'), table_name='policies')
    op.drop_index(op.f('ix_policies_current_version_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_plans_tenant_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_status'), table_name='plans')
    op.drop_index(op.f('ix_plans_planner_trace_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_index(op.f('ix_plans_chat_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_agent_run_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('orchestration_settings')
    op.drop_index(op.f('ix_limits_slug'), table_name='limits')
    op.drop_index(op.f('ix_limits_current_version_id'), table_name='limits')
    op.drop_table('limits')
    op.drop_index('ix_events_outbox_type', table_name='events_outbox')
    op.drop_index('ix_events_outbox_seq', table_name='events_outbox')
    op.drop_index('ix_events_outbox_delivered_created', table_name='events_outbox')
    op.drop_index('ix_events_outbox_delivered_at', table_name='events_outbox')
    op.drop_index('ix_events_outbox_created_at', table_name='events_outbox')
    op.drop_table('events_outbox')
    op.drop_index(op.f('ix_collections_tenant_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_current_version_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_collection_versions_status'), table_name='collection_versions')
    op.drop_index(op.f('ix_collection_versions_collection_id'), table_name='collection_versions')
    op.drop_table('collection_versions')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.drop_index('ix_api_keys_tenant_id', table_name='api_keys')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.drop_index(op.f('ix_agents_current_version_id'), table_name='agents')
    op.drop_table('agents')
    op.create_foreign_key('fk_agents_user_id_deferred', 'agents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_role_id_deferred', 'agents', 'system_llm_roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_chat_id_deferred', 'agents', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_agent_run_id_deferred', 'agents', 'agent_runs', ['agent_run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_user_message_id_deferred', 'agents', 'chatmessages', ['user_message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_user_id_deferred', 'agents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_chat_id_deferred', 'agents', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_assistant_message_id_deferred', 'agents', 'chatmessages', ['assistant_message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_agent_run_id_deferred', 'agents', 'agent_runs', ['agent_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_run_id_deferred', 'agents', 'agent_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_owner_id_deferred', 'agents', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_message_id_deferred', 'agents', 'chatmessages', ['message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_chat_id_deferred', 'agents', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_user_id_deferred', 'agents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_message_id_deferred', 'agents', 'chatmessages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_chat_id_deferred', 'agents', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_session_id_deferred', 'agents', 'sandbox_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_document_id_deferred', 'agents', 'ragdocuments', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_doc_id_deferred', 'agents', 'ragdocuments', ['doc_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_chat_id_deferred', 'agents', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_source_id_deferred', 'agents', 'sources', ['source_id'], ['source_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_source_id_deferred', 'agents', 'sources', ['source_id'], ['source_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_chat_id_deferred', 'agents', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_chat_id_deferred', 'agents', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_user_id_deferred', 'agents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_owner_id_deferred', 'agents', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_user_id_deferred', 'agents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_owner_user_id_deferred', 'agents', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_owner_tenant_id_deferred', 'agents', 'tenants', ['owner_tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_created_by_user_id_deferred', 'agents', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_uploaded_by_deferred', 'agents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_owner_user_id_deferred', 'agents', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_owner_tenant_id_deferred', 'agents', 'tenants', ['owner_tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_instance_id_deferred', 'agents', 'tool_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_owner_id_deferred', 'agents', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_embedding_model_alias_deferred', 'agents', 'models', ['embedding_model_alias'], ['alias'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_run_id_deferred', 'agents', 'sandbox_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_updated_by_deferred', 'agents', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_branch_id_deferred', 'agents', 'sandbox_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_prompt_id_deferred', 'agents', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_parent_version_id_deferred', 'agents', 'prompt_versions', ['parent_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_policy_id_deferred', 'agents', 'policies', ['policy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_parent_version_id_deferred', 'agents', 'policy_versions', ['parent_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_instance_id_deferred', 'agents', 'tool_instances', ['instance_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_parent_version_id_deferred', 'agents', 'limit_versions', ['parent_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_limit_id_deferred', 'agents', 'limits', ['limit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_tool_id_deferred', 'agents', 'tools', ['tool_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_provider_instance_id_deferred', 'agents', 'tool_instances', ['provider_instance_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_collection_id_deferred', 'agents', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_user_id_deferred', 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_parent_version_id_deferred', 'agents', 'agent_versions', ['parent_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_agent_id_deferred', 'agents', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_current_version_id_deferred', 'agents', 'tool_releases', ['current_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tool_id_deferred', 'agents', 'tools', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_parent_release_id_deferred', 'agents', 'tool_releases', ['parent_release_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_backend_release_id_deferred', 'agents', 'tool_backend_releases', ['backend_release_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_access_via_instance_id_deferred', 'agents', 'tool_instances', ['access_via_instance_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tool_id_deferred', 'agents', 'tools', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_snapshot_id_deferred', 'agents', 'sandbox_override_snapshots', ['snapshot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_session_id_deferred', 'agents', 'sandbox_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_parent_run_id_deferred', 'agents', 'sandbox_runs', ['parent_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_branch_id_deferred', 'agents', 'sandbox_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_session_id_deferred', 'agents', 'sandbox_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_created_by_deferred', 'agents', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_branch_id_deferred', 'agents', 'sandbox_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_session_id_deferred', 'agents', 'sandbox_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_parent_run_id_deferred', 'agents', 'sandbox_runs', ['parent_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_parent_branch_id_deferred', 'agents', 'sandbox_branches', ['parent_branch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_created_by_deferred', 'agents', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_recommended_version_id_deferred', 'agents', 'prompt_versions', ['recommended_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_current_version_id_deferred', 'agents', 'policy_versions', ['current_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_current_version_id_deferred', 'agents', 'limit_versions', ['current_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_tenant_id_deferred', 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_data_instance_id_deferred', 'agents', 'tool_instances', ['data_instance_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_current_version_id_deferred', 'agents', 'collection_versions', ['current_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agents_current_version_id_deferred', 'agents', 'agent_versions', ['current_version_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
